heat_template_version: 2015-04-30

description: >
  HOT template to create a PhysicalInterface:

parameters:
  name:
    type: string
    description: name for the PhysicalInterface
    # required: optional
  fq_name:
    type: string
    description: fq_name for the PhysicalInterface
    # required: optional
  display_name:
    type: string
    description: Display name user configured string(name) that can be updated any time. Used as openstack name.
    # operations: CRUD
    # required: optional
  annotations_key_value_pair_key:
    type: string
    description: key for the PhysicalInterface
    # operations: CRUD
    # required: optional
  annotations_key_value_pair_value:
    type: string
    description: value for the PhysicalInterface
    # operations: CRUD
    # required: optional
  physical_interface_refs:
    type: string
    description: Reference to the other physical interface that is connected to this  physical interface.
    # required: optional
  physical_router:
    type: string
    description: physical_router for the PhysicalInterface
    # required: optional

resources:
  template_PhysicalInterface:
    type: OS::ContrailV2::PhysicalInterface
    properties:
      name: { get_param: name }
      fq_name: { get_param: fq_name }
      display_name: { get_param: display_name }
      annotations:
        {
          annotations_key_value_pair:
            [{
              annotations_key_value_pair_key: { get_param: annotations_key_value_pair_key },
              annotations_key_value_pair_value: { get_param: annotations_key_value_pair_value },
            }],
        }
      physical_interface_refs: [{ get_param: physical_interface_refs }]
      physical_router: { get_param: physical_router }

