heat_template_version: 2015-04-30

description: >
  HOT template to create a PortTuple:

parameters:
  name:
    type: string
    description: name for the PortTuple
    # required: optional
  fq_name:
    type: string
    description: fq_name for the PortTuple
    # required: optional
  display_name:
    type: string
    description: Display name user configured string(name) that can be updated any time. Used as openstack name.
    # operations: CRUD
    # required: optional
  annotations_key_value_pair_key:
    type: string
    description: key for the PortTuple
    # operations: CRUD
    # required: optional
  annotations_key_value_pair_value:
    type: string
    description: value for the PortTuple
    # operations: CRUD
    # required: optional
  service_instance:
    type: string
    description: service_instance for the PortTuple
    # required: optional

resources:
  template_PortTuple:
    type: OS::ContrailV2::PortTuple
    properties:
      name: { get_param: name }
      fq_name: { get_param: fq_name }
      display_name: { get_param: display_name }
      annotations:
        {
          annotations_key_value_pair:
            [{
              annotations_key_value_pair_key: { get_param: annotations_key_value_pair_key },
              annotations_key_value_pair_value: { get_param: annotations_key_value_pair_value },
            }],
        }
      service_instance: { get_param: service_instance }

