heat_template_version: 2015-04-30

description: >
  HOT template to create a VirtualMachine:

parameters:
  name:
    type: string
    description: name for the VirtualMachine
    # required: optional
  fq_name:
    type: string
    description: fq_name for the VirtualMachine
    # required: optional
  display_name:
    type: string
    description: Display name user configured string(name) that can be updated any time. Used as openstack name.
    # operations: CRUD
    # required: optional
  annotations_key_value_pair_key:
    type: string
    description: key for the VirtualMachine
    # operations: CRUD
    # required: optional
  annotations_key_value_pair_value:
    type: string
    description: value for the VirtualMachine
    # operations: CRUD
    # required: optional
  service_instance_refs:
    type: string
    description: Reference to the service instance of this virtual machine.
    # required: optional

resources:
  template_VirtualMachine:
    type: OS::ContrailV2::VirtualMachine
    properties:
      name: { get_param: name }
      fq_name: { get_param: fq_name }
      display_name: { get_param: display_name }
      annotations:
        {
          annotations_key_value_pair:
            [{
              annotations_key_value_pair_key: { get_param: annotations_key_value_pair_key },
              annotations_key_value_pair_value: { get_param: annotations_key_value_pair_value },
            }],
        }
      service_instance_refs: [{ get_param: service_instance_refs }]

